from trytond.pool import Pool

from . import base_object
from . import measurement
from . import address
from . import object_party
from . import contract_core
from . import contract_type
from . import contract_item
from . import contract_term
from . import contract_party
from . import contract_rent_adjustment
from . import contract_wizard
from . import contract_report
from . import sequence
from . import res
from . import ir
from . import party
from . import invoice
from . import company
from . import re_accounting
from . import cron_task
from . import billing_unit
from . import billing_unit_wizard
from . import settlement_unit
from . import settlement_result
from . import option_rate
from . import option_rate_wizard
from . import co2_kostaufg
from . import bved
from . import price_index
from . import contract_index_rent
from . import task
from . import task_rule
from . import process
from . import handover
from . import meter_reading_sheet
from . import rent_survey
from . import adjustment_run
from . import contract_comparative_rent
from . import inspection

__all__ = ['register']


def register():
    Pool.register(
        address.Address,
        measurement.MeasurementType,
        measurement.Measurement,
        measurement.MeasurementContext,
        base_object.UseClass,
        base_object.BaseObject,
        base_object.BaseObjectEquipmentContext,
        base_object.BaseObjectCompanyContext,
        base_object.BaseObjectContext,
        base_object.BaseObjectOccupancy,
        base_object.BaseObjectOccupancyContext,
        base_object.MeterReadingContext,
        base_object.MeterReading,
        base_object.EstimateConsumptionStart,
        base_object.EstimateConsumptionResult,
        object_party.ObjectPartyRole,
        object_party.ObjectParty,
        contract_core.ContractContext,
        contract_core.ContractLog,
        contract_core.ContractLogContext,
        contract_core.AccountContract,
        contract_core.GeneralLedgerAccountContract,
        contract_core.ContractGeneralLedgerAccountContractContext,
        contract_core.Contract,
        contract_type.UseClass,
        contract_type.ContractTypeTax,
        contract_type.ContractType,
        contract_type.ContractTermType,
        contract_type.ContractTermTypeCType,
        contract_item.ContractItemObject,
        contract_item.ContractItem,
        contract_term.ContractTermTax,
        contract_term.ContractTermCashFlow,
        contract_term.ContractTermCashFlowContext,
        contract_term.ContractTerm,
        contract_term.ContractTermAdjustment,
        contract_rent_adjustment.ContractRentAdjustment,
        contract_rent_adjustment.Contract,
        contract_party.ContractPartyRoleCType,
        contract_party.ContractPartyRole,
        contract_party.ContractParty,
        contract_wizard.CreateContractMovesStart,
        contract_wizard.CreateContractMovesConfirm,
        contract_wizard.CreateContractMovesResult,
        contract_wizard.CancelPeriodBookingStart,
        contract_wizard.TerminateContractStart,
        contract_wizard.ChangeContractPartnerStart,
        billing_unit_wizard.BillingUnitStart,
        billing_unit_wizard.BillingUnitConfirm,
        billing_unit_wizard.BillingUnitResult,
        billing_unit_wizard.CancelBillingStart,
        billing_unit_wizard.ReconcileAdvancePaymentsStart,
        billing_unit_wizard.ReconcileAdvancePaymentsResult,
        #sequence.Sequence,
        res.User,
        ir.Cron,
        party.Party,
        invoice.Invoice,
        invoice.InvoiceLine,
        invoice.AccountMoveLine,
        invoice.ContractMoveLinePayableReceivableContext,
        invoice.ContractMoveLinePayableReceivableRelateContext,
        invoice.GeneralLedgerLine,
        company.Company,
        re_accounting.ReAccounting,
        cron_task.CronTask,
        billing_unit.CostCategoryGroup,
        billing_unit.CostType,
        billing_unit.BillingUnitContext,
        billing_unit.BillingUnitLogContext,
        billing_unit.BillingUnit,
        billing_unit.BillingUnitLog,
        billing_unit.BillingUnitMoves,
        billing_unit.BillingUnitMovesContext,
        settlement_unit.SettlementUnitContext,
        settlement_unit.SettlementUnit,
        settlement_result.CostShareContext,
        settlement_result.SettlementResultContext,
        settlement_result.CostShare,
        settlement_result.SettlementResult,
        price_index.PriceIndex,
        price_index.PriceIndexValue,
        price_index.PriceIndexValueContext,
        price_index.PriceIndexImportStart,
        price_index.PriceIndexImportPreview,
        price_index.PriceIndexImportResult,
        price_index.IndexCapRule,
        contract_index_rent.ContractRentAdjustment,
        contract_index_rent.ContractTermAdjustment,
        price_index.Contract,
        task.TaskType,
        task.Task,
        task.TaskPostponeStart,
        task.TaskCreateStart,
        task.Contract,
        task.RentAdjustment,
        task.BillingUnit,
        task.BaseObject,
        task.User,
        task_rule.TaskRule,
        task_rule.Contract,
        process.ProcessTemplate,
        process.ProcessTemplateStep,
        process.Process,
        process.Task,
        process.ProcessStartStart,
        process.RentAdjustment,
        process.BillingUnit,
        process.BaseObject,
        process.ContractType,
        process.Contract,
        handover.HandoverChecklist,
        handover.HandoverChecklistLine,
        handover.Handover,
        handover.HandoverObject,
        handover.HandoverParty,
        handover.HandoverLine,
        handover.HandoverKey,
        handover.HandoverMeter,
        handover.Contract,
        handover.Process,
        inspection.EquipmentKind,
        inspection.BaseObject,
        inspection.InspectionChecklist,
        inspection.InspectionChecklistItem,
        inspection.InspectionType,
        inspection.InspectionPlan,
        inspection.Inspection,
        inspection.InspectionParty,
        inspection.InspectionLine,
        inspection.InspectionResult,
        inspection.InspectionPlanP2,
        inspection.Contract,
        inspection.Process,
        inspection.BaseObjectP2,
        inspection.InspectionDefect,
        inspection.InspectionP4,
        inspection.InspectionResultP4,
        inspection.InspectionLineP4,
        inspection.ProcessP4,
        inspection.BaseObjectP4,
        inspection.TaskRule,
        meter_reading_sheet.MeterReadingSheet,
        meter_reading_sheet.MeterReadingSheetLine,
        rent_survey.RentSurvey,
        rent_survey.RentSurveyVersion,
        rent_survey.RentSurveyVersionMeasurementType,
        rent_survey.RentSurveyDimension,
        rent_survey.RentSurveyDimensionClass,
        rent_survey.RentSurveyCell,
        rent_survey.RentSurveyCellClass,
        rent_survey.RentSurveyGroup,
        rent_survey.RentSurveyFeature,
        rent_survey.RentSurveyFeatureClass,
        rent_survey.RentSurveyFeatureFeature,
        rent_survey.RentSurveyImportStart,
        rent_survey.RentSurveyImportPreview,
        rent_survey.RentSurveyNewVersionStart,
        rent_survey.BaseObjectRentSurveyValue,
        rent_survey.BaseObject,
        rent_survey.RentSurveyFeaturesStart,
        rent_survey.RentSurveyCopyStart,
        rent_survey.RentSurveyMatrixExportStart,
        rent_survey.RentSurveyMatrixExportResult,
        rent_survey.RentSurveyMatrixImportStart,
        rent_survey.RentSurveyMatrixImportPreview,
        rent_survey.RentSurveyCalculation,
        adjustment_run.ContractTermAdjustmentRun,
        adjustment_run.ContractTermAdjustmentRunProperty,
        adjustment_run.ContractTermAdjustmentRunContract,
        adjustment_run.ContractTermAdjustment,
        adjustment_run.Process,
        contract_comparative_rent.ContractRentAdjustment,
        contract_comparative_rent.ContractTermAdjustment,
        contract_comparative_rent.AdjustmentRunAddStart,
        ir.Rule,
        option_rate.OptionRateContext,
        option_rate.OptionRate,
        option_rate_wizard.OptionRateUpdateStart,
        option_rate_wizard.OptionRateUpdateConfirm,
        option_rate_wizard.OptionRateUpdateResult,
        co2_kostaufg.Co2KostAufg,
        co2_kostaufg.Co2KostAufgConsumption,
        co2_kostaufg.Co2KostAufgConsumptionEnergyMix,
        co2_kostaufg.Co2EmissionShare,
        bved.BvedUnit,
        bved.BvedServiceProvider,
        bved.BvedProviderAssignment,
        bved.BvedObjectNumber,
        bved.BvedObjectNumberMSatzLine,
        bved.BvedExportBillingUnit,
        bved.BvedExport,
        bved.BvedImport,
        bved.BvedImportLine,
        module='real_estate', type_='model')
    Pool.register(
        contract_wizard.CreateContractMovesWizard,
        contract_wizard.CancelPeriodBookingWizard,
        contract_wizard.ChangeContractPartnerWizard,
        contract_wizard.TerminateContractWizard,
        contract_wizard.ContractRunningWizard,
        base_object.EstimateConsumptionWizard,
        billing_unit_wizard.BillingUnitWizard,
        billing_unit_wizard.CancelBillingWizard,
        billing_unit_wizard.ReconcileAdvancePaymentsWizard,
        contract_wizard.OpenContractSettlementUnits,
        option_rate_wizard.OptionRateUpdateWizard,
        price_index.PriceIndexImport,
        task.TaskPostpone,
        task.TaskCreate,
        process.TaskExecuteAction,
        inspection.InspectionNoticeCreate,
        inspection.InspectionAccessLetterCreate,
        process.ProcessStart,
        process.TerminateContractWizard,
        process.ChangeContractPartnerWizard,
        rent_survey.RentSurveyImport,
        rent_survey.RentSurveyNewVersion,
        rent_survey.RentSurveyFeatures,
        rent_survey.RentSurveyCopy,
        rent_survey.RentSurveyMatrixExport,
        rent_survey.RentSurveyMatrixImport,
        contract_comparative_rent.AdjustmentRunAdd,
        module='real_estate', type_='wizard')
    Pool.register(
        base_object.BaseObjectReport,
        contract_report.ContractReport,
        inspection.InspectionReport,
        inspection.InspectionNoticeReport,
        inspection.InspectionAccessLetterReport,
        contract_report.ContractAnnex4Report,
        contract_report.ContractTerminationConfirmationReport,
        contract_report.IndexAdjustmentLetterReport,
        contract_report.ComparativeRentLetterReport,
        contract_report.HandoverReport,
        meter_reading_sheet.MeterReadingSheetReport,
        invoice.ContractMoveLinePayableReceivableReport,
        contract_core.ContractGeneralLedgerAccountContractReport,
        module='real_estate', type_='report')
